# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "415f4f6f5a2b9bbe6ec041251e753694"
name = "LookSpot"
application_url = "https://shopspot.solnix.store"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [webhooks.privacy_compliance]
  customer_data_request_url = "/api/webhooks"
  customer_deletion_url = "/api/webhooks"
  shop_deletion_url = "/api/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopspot.solnix.store/api/auth" ]

[app_preferences]
url = "https://shopspot.solnix.store"
